### ISSUE TITLE
Review MdcCascadingDefaults

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#10]
I have a lurking suspicion that there is a better approach. Just not sure yet what that would be!

**Comment by simonziegler** [comment]
I agree there is probably a better way, and likewise haven't concluded what it may be.

**Comment by MarkStega** [comment]
Discuss single text style default versus a default for each use. If we keep single I think there should be only one applied style method.

**Comment by simonziegler** [comment]
Agree to single text style. It would be stylistic mayhem to make them different, and this cleans things up.

**Comment by MarkStega** [comment]
I suggest that if there is a single button style then
```
        public MdcButtonStyle ButtonStyle { get; set; } = MdcButtonStyle.Text;
        public MdcButtonStyle CardActionButtonStyle { get; set; } = MdcButtonStyle.Text;
        public MdcButtonStyle DialogActionButtonStyle { get; set; } = MdcButtonStyle.Text;
        internal MdcButtonStyle AppliedStyle(MdcButtonStyle? style = null) => (style is null) ? ButtonStyle : (MdcButtonStyle)style;
        internal MdcButtonStyle AppliedStyle_CardActionButton(MdcButtonStyle? style = null) => (style is null) ? CardActionButtonStyle : (MdcButtonStyle)style;
        internal MdcButtonStyle AppliedStyle_DialogActionButton(MdcButtonStyle? style = null) => (style is null) ? DialogActionButtonStyle : (MdcButtonStyle)style;
```
should just be 
```
        public MdcButtonStyle ButtonStyle { get; set; } = MdcButtonStyle.Text;
        internal MdcButtonStyle AppliedStyle(MdcButtonStyle? style = null) => (style is null) ? ButtonStyle : (MdcButtonStyle)style;
```

**Comment by MarkStega** [comment]
And I'd suggest the same for the validation methods.

**Comment by simonziegler** [comment]
I have a case where I would like card buttons to default to something different to other buttons. For my project I want card buttons to be Text while others should be ContainedUnelevated.
