### ISSUE TITLE
Datepicker format enhancement

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#119]
Consider adding a parameter to the DatePicker of something like DateFormat. If you can pass in a format string like "ddd, MMM dd yyyy" and that gets passed down to Utilities.DateToString (which already has the format parameter, but it is not used) you can avoid a common overflow situation which is caused by the default "D" formatting. The parameter needs to get used in DatePicker and passed on to InternalDatePickerPanel to be used it its call. The parameter could have a default value of "D" and the parameter in DateToString could have the null indicator removed.

**Comment by simonziegler** [comment]
Closed by #115
