### ISSUE TITLE
Remove Backing Value control mechanism

### ISSUE THREAD

**Issue by simonziegler** [Material-Blazor/Material.Blazor#198]
MTPaginator and MTPagedDataList both adjusted their page number and items per page ValueChanged mechanism in line with https://github.com/dotnet/aspnetcore/issues/24599, using the pattern of Component1a in the reference repo https://github.com/simonziegler/TwoWayBindingDemo/blob/main/TwoWayBindingDemo/Shared/Component1a.razor.

Revert once this issue is resolved by the ASP.NET team.

**Comment by MarkStega** [comment]
ASP.Net team has closed https://github.com/dotnet/aspnetcore/issues/24599 basically stating that our programming pattern is wrong. We need to understand and see if we concur and. if so, make changes as needed.

**Comment by simonziegler** [comment]
This implemented as a trial for the `PageNumber` property of `MBPagedDataList`
