### ISSUE TITLE
Incremental builds

### ISSUE THREAD

**Issue by simonziegler** [Material-Blazor/Material.Blazor#204]
- Build
    - [x] Make CSS and JS/TS changes 'force' a build
    - [x] Make CSS and JS/TS compilation conditional

**Comment by MarkStega** [comment]
Conditional builds are implemented in the two relevant .csproj files. Unfortunately, in VS 16.8.0 Preview 3.1 the 'force' aspect of the build does not occur (it does when the project is built with "dotnet build"
