### ISSUE TITLE
Documentation review prior to release candidates

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#239]
- [x] Anchor - Demo page
- [x] Anchor - Example card(s)
- [x] Anchor - Page links
<br/>

- [x] AnimatedNavigationmanager- Demo page
- [x] AnimatedNavigationmanager- Page links
- [x] AnimatedNavigationmanager- Example card(s)
<br/>

- [x] AutocompleteTextField - Demo page
- [x] AutocompleteTextField - Page links
- [x] AutocompleteTextField - Example card(s)
<br/>

- [x] Button - Demo page
- [x] Button - Page links
- [x] Button - Example card(s)
<br/>

- [x] Card - Demo page
- [x] Card - Page links
- [x] Card - Example card(s)
<br/>

- [x] CascadingDefaults - Demo page
- [x] CascadingDefaults - Page links
- [x] CascadingDefaults - Example card(s)
<br/>

- [x] Checkbox - Demo page
- [x] Checkbox - Page links
- [x] Checkbox - Example card(s)
<br/>

- [x] CircularProgress - Demo page
- [x] CircularProgress - Page links
- [x] CircularProgress - Example card(s)
<br/>

- [x] ConfirmationDialog - Demo page
- [x] ConfirmationDialog - Page links
- [x] ConfirmationDialog - Example card(s)
<br/>

- [x] DataTable - Demo page
- [x] DataTable - Page links
- [x] DataTable - Example card(s)
<br/>

- [x] DatePicker - Demo page
- [x] DatePicker - Page links
- [x] DatePicker - Example card(s)
<br/>

- [x] DebouncedTextField - Demo page
- [x] DebouncedTextField - Page links
- [x] DebouncedTextField - Example card(s)
<br/>

- [x] Dialog - Demo page
- [x] Dialog - Page links
- [x] Dialog - Example card(s)
<br/>

- [x] Divider - Demo page
- [x] Divider - Page links
- [x] Divider - Example card(s)
<br/>

- [x] Drawer - Demo page
- [x] Drawer - Page links
- [x] Drawer - Example card(s)
<br/>

- [x] Icon - Demo page
- [x] Icon - Page links
- [x] Icon - Example card(s)
<br/>

- [x] IconButton - Demo page
- [x] IconButton - Page links
- [x] IconButton - Example card(s)
<br/>

- [x] IconButtonToggle - Demo page
- [x] IconButtonToggle - Page links
- [x] IconButtonToggle - Example card(s)
<br/>

- [x] LinearProgress - Demo page
- [x] LinearProgress - Page links
- [x] LinearProgress - Example card(s)
<br/>

- [x] List - Demo page
- [x] List - Page links
- [x] List - Example card(s)
<br/>

- [x] Menu - Demo page
- [x] Menu - Page links
- [x] Menu - Example card(s)
<br/>

- [x] NumericDoubleField - Demo page
- [x] NumericDoubleField - Page links
- [x] NumericDoubleField - Example card(s)
<br/>

- [x] NumericIntField - Demo page
- [x] NumericIntField - Page links
- [x] NumericIntField - Example card(s)
<br/>

- [x] PagedDataList - Demo page
- [x] PagedDataList - Page links
- [x] PagedDataList - Example card(s)
<br/>

- [x] Paginator - Demo page
- [x] Paginator - Page links
- [x] Paginator - Example card(s)
<br/>

- [x] RadioButton - Demo page
- [x] RadioButton - Page links
- [x] RadioButton - Example card(s)
<br/>

- [x] RadioButtonGroup - Demo page
- [x] RadioButtonGroup - Page links
- [x] RadioButtonGroup - Example card(s)
<br/>

- [x] Select - Demo page
- [x] Select - Page links
- [x] Select - Example card(s)
<br/>

- [x] Shield - Demo page
- [x] Shield - Page links
- [x] Shield - Example card(s)
<br/>

- [x] SlidingContent - Demo page
- [x] SlidingContent - Page links
- [x] SlidingContent - Example card(s)
<br/>

- [x] SlidingTabBar - Demo page
- [x] SlidingTabBar - Page links
- [x] SlidingTabBar - Example card(s)
<br/>

- [x] Switch - Demo page
- [x] Switch - Page links
- [x] Switch - Example card(s)
<br/>

- [x] TabBar - Demo page
- [x] TabBar - Page links
- [x] TabBar - Example card(s)
<br/>

- [x] TextArea - Demo page
- [x] TextArea - Page links
- [x] TextArea - Example card(s)
<br/>

- [x] TextField - Demo page
- [x] TextField - Page links
- [x] TextField - Example card(s)
<br/>

- [x] Toast - Demo page
- [x] Toast - Page links
- [x] Toast - Example card(s)
<br/>

- [x] Tooltip - Demo page
- [x] Tooltip - Page links
- [x] Tooltip - Example card(s)
<br/>

- [x] TopAppBar - Demo page
- [x] TopAppBar - Page links
- [x] TopAppBar - Example card(s)
<br/>

- [x] Typography- Demo page
- [x] Typography- Page links
- [x] Typography- Example card(s)
<br/>

**Issues**

- [x] DemonstrationPage -- Links all refer to BlazorMdc.com regardless of build/publish location -- Leave 'as is'
- [x] SlidingTabBar -- Content render fragment issue -- Visual Studio issue
- [x] Build shields need updating in documentation (SZ)
- [x] ~Switch seems to use a different font for labels than other controls (SZ)~
- [ ] ~Articles that need to be verified - CascadingDefaults, Introduction (SZ)~
- [x] Articles that need to be written - AnimatedNavigation, Icon, ReleaseNotes, Toast, Tooltip (SZ)
<br/>

**Breaking changes (SZ - Need documentation in ReleaseNotes article)**

- [ ] ~MTAnimatedNavigationManagerConfiguration -> MTAnimatedNavigationServiceConfiguration to be consistent with ToastService & TooltipService~
- [ ] ~MTAutocomplete -> MTAutocompleteTextField to be consistent with MTDebouncedTextField & MTTextField~
- [ ] ~MTNumericIntField/MTNumericDoubleField - Focussed -> Focused parameters~

**Comment by simonziegler** [comment]
MTSwitch implements material theme's switch markup correctly: https://github.com/material-components/material-components-web/tree/master/packages/mdc-switch#switch-example

**Comment by simonziegler** [comment]
Animated navigation manager interface and class names have been refined.

**Comment by simonziegler** [comment]
Build shields to be updated after migration to replacement for existing "Blazor MDC" repo/package name.
