### ISSUE TITLE
Prefix/Suffix alignment in text box on mobile/safari (Material issue)

### ISSUE THREAD

**Issue by gismofx** [Material-Blazor/Material.Blazor#242]
See attached screen recording. Prefix and suffix alignment issues with default and outlined text box on mobile safari.

[Screen recording](https://imgur.com/a/tAWKfKu)

**Comment by simonziegler** [comment]
@gismofx I believe that this is an issue with Google's Material Components Web at https://simonziegler.github.io/MaterialIssues/ and have raised the issue with MCW that you will see above.

**Comment by simonziegler** [comment]
This problem mostly goes away with Material Components Web 8.0.0 with outlined text fields behaving properly and filled text fields slightly wrong:

- Outlined text fields now appear to behave well with prefixes, suffixes and input text all properly aligned.
- Filled text fields are still problematic. The first time you type some text in it is raised too high. When you subsequently edit the input aligns correctly.

Material.Blazor version 2.0.0 will upgrade to Material Components Web 8.0.0 and will be released probably by late November 2020.

**Comment by MarkStega** [comment]
Since this is a Material issue that is manifesting itself in Material.Blazor this bug report will be closed by the release of 2.0.

Tracking of the Material issue is at [https://github.com/material-components/material-components-web/issues/6601](https://github.com/material-components/material-components-web/issues/6601)

**Comment by MarkStega** [comment]
This needs to be tested again with the move to Material 9.0.0

**Comment by simonziegler** [comment]
Having updated to material-components-web 9.0.0 this issue is now resolved for outlined text fields but not for the filled variant. I'll take a look at our filled markup to ensure that it is correct.

**Comment by simonziegler** [comment]
Issue no longer present in MCW 12
