### ISSUE TITLE
MBGrid requirements

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#243]
MBGrid Phase 1

- [x] Horizontal & vertical scrolling keeping column headers in view
- [x] Grouping with a separate template for the group names
- [x] Individual column templates, some data will be graphical
- [x] Ability to visually suppress columns (i.e. the 'group by' column)
- [x] Need to update backing data (as little as one column of one row and get a smooth refresh)
- [x] Fixed width column
- [x] 'Fit to data' column width
- [x] Multi column sorting

MBGrid Phase 2

- [ ] Material styling
- [ ] Density support

MBGrid Phase 3 Candidates

- [ ] Column filtering - Filter methods for common datatypes (string & numeric) and extension custom filter dialog, details TBD
- [ ] Column render fragments
- [ ] Dynamic 'fit to content'
- [ ] Move all data manipulation (Sorting, grouping, etc.) to the responsibility of the grid 'owner'
- [ ] Virtualization

**Comment by stefanloerwald** [comment]
I'd like to add filtering to the wishlist. Ideally, this would include a set of filter methods for common datatypes (string and numerical data) and the ability to extend that with a custom filter dialog and method (I need to work out a nice way to integrate custom filtering, not sure about the syntax yet).

[MS - 2020-09-05] Added requirement bullet with details TBD

**Comment by stefanloerwald** [comment]
Thinking about the custom filter menu:

The user should not be required to write a menu component and should not have to deal with how to open/close the menu. All they should provide is the content of the menu.
What they need for that is
- context about what is available to display
- some means to indicate back to the grid component that the table should be filtered by a particular predicate

I'm fairly sure we can design it roughly like this, so that usage looks like:

```html
<Column Header="Column with customized filter">
   <CustomFilterMenuContent>
      @foreach (var item in context.Items)
      {
         <MTCheckbox Value="context.IsVisible(item)"
               ValueChanged="(visible) => { UpdateFilter(context, item, visible); }"/>
      }
   </CustomFilterMenuContent>
</Column>
@code {
  private List<TItem> my_visible_items = new List<TItem>();
  private void UpdateFilter(ColumnFilterContext<TItem> context, TItem item, bool visible)
  {
      if (visible) 
      {
         my_visible_items.Add(item);
      }
      else
      {
         my_visible_items.Remove(item);
      }
      // this is how we could update the filter: we replace the filter predicate
      context.IsVisible = (i) => my_visible_items.Contains(i);
  }
}
```

This of course is a rather boring filter menu (simply listing all items? come on!)

A more interesting one could be 

```html
<Column Header="SomeValue">
   <CustomFilterMenuContent>
      <MTNumericDoubleField Value="threshold"
            ValueChanged="(v) => {threshold = v;  context.IsVisible = (i) => { i.SomeValue > threshold; }; } />
   </CustomFilterMenuContent>
</Column>
@code {
  private double threshold;
}
```

So I think the definition could be:
```cs
public class ColumnFilterContext<TItem>
{
   public IEnumerable<TItem> Items { get; } //  to think about: is IEnumerable a good choice here?
   public Func<TItem, bool> IsVisible { get; set; } = (_) => true; // default state is to have everything visible
}
```

And for the column:

```cs
public partial class Column
{
    [Parameter] public string Header {get;set;}
    [Parameter] public RenderFragment<ColumnFilterContext<TItem>> CustomFilterMenuContent {get;set;}
    //...
}
```

Disclaimer: none of this code is tested. It wasn't even compiled once, so might contain syntax errors and other issues.

**Comment by simonziegler** [comment]
Is there anything in ASP.NET rc 1 that should be used to enhance a grid? E.g. Virtualize

**Comment by MarkStega** [comment]
MBGrid Phase 2 Candidates

- [ ] Column filtering - Filter methods for common datatypes (string & numeric) and extension custom filter dialog, details TBD
- [ ] Dynamic 'fit to content'
- [ ] Virtualization

**Comment by MarkStega** [comment]
Closing as the path forward is in [MBGridMT](https://github.com/Material-Blazor/Material.Blazor/issues/567)
