### ISSUE TITLE
Wrong documentation in the installation section 

### ISSUE THREAD

**Issue by arkiaman** [Material-Blazor/Material.Blazor#255]
The documentation says to add css and js references to index.html. The link to these files is wrong

It should be:
`<link href="_content/Material.Blazor/material.blazor.material-bundle.min.css" rel="stylesheet">`

instead of
`<link href="_content/Material-Blazor/material.blazor.material-bundle.min.css" rel="stylesheet">`

Same for the js reference

**Comment by simonziegler** [comment]
We may change the bundle css and js name today as we move to release candidate 1. Please check the docs after that release for certainty.
