### ISSUE TITLE
Feature request for MBDialog: hide title when empty

### ISSUE THREAD

**Issue by stefanloerwald** [Material-Blazor/Material.Blazor#284]
When the title of an MBDialog is empty, the whitespace around the body feels unbalanced.

As a workaround, I'm using
```css
.mdc-dialog__title {
    height: 20px;
}
```

for when the dialog doesn't have a title. Not sure how to actually resolve this elegantly. I'd guess, there shouldn't even be a heading element when there is no title, but I don't know how mdc handles those cases.

**Comment by simonziegler** [comment]
We need to investigate MBDialog's implementation to see if we should only render titles when they are not null or whitespace.

**Comment by simonziegler** [comment]
MBDialog needs improvement to make both the title and the body divs render only if there's data. Also impacts aria attributes.
