### ISSUE TITLE
package.json added to project by Nuget Package

### ISSUE THREAD

**Issue by IvanJosipovic** [Material-Blazor/Material.Blazor#286]
After adding Material.Blazor 1.0.0-rc.4, I see a package.json has been added from this NuGet package.

![image](https://user-images.githubusercontent.com/9521987/95257921-e0751800-07d9-11eb-89e2-53ad90a3d255.png)

I belive the fix is to add the following to Material.Blazor.csproj
```
  <ItemGroup>
    <Content Update="package.json">
      <Pack>false</Pack>
    </Content>
  </ItemGroup>
```

**Comment by MarkStega** [comment]
Its easier just to change the "build action" to none in the properties window of VS. I did this & the next RC will not exhibit this issue.

Thanks for the report!
