### ISSUE TITLE
Review @key use across all components

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#30]
@key appears to be used in situations where it isn't a contributor

**Comment by simonziegler** [comment]
I suspect this may be the other way around. We need every loop displaying content to use `@key`. This was added to MdcMenu and MdcDataTable in a recent commit having been pointed out by @mrpmorris.

**Comment by simonziegler** [comment]
Does this still need to be open?

**Comment by mrpmorris** [comment]
You only need key when markup is generated in a loop of some kind. In those cases, I recommend always using it.
