### ISSUE TITLE
Website is broken (?) 

### ISSUE THREAD

**Issue by tesar-tech** [Material-Blazor/Material.Blazor#322]
I switched themes in right upper corner and this happened :
![image](https://user-images.githubusercontent.com/33880579/98085782-24f9df00-1e7e-11eb-97dd-809848ec1d7f.png)

Errors from console: 
![image](https://user-images.githubusercontent.com/33880579/98085888-478bf800-1e7e-11eb-8dd5-651b11334593.png)

**Comment by MarkStega** [comment]
My fault - I missed several name changes of a project; The site willl be published on the next release.
