### ISSUE TITLE
Disabled parameter needs review

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#344]
The Disable parameter is implemented in ComponentBase. Should it be, instead, in InputComponentBase?

I can't imagine what disabling means to non-interactive components. A shield, card, icon, and paginator are a few examples where disabled doesn't seem to make sense.

Are there any examples where it does make sense?

**Comment by simonziegler** [comment]
Buttons use ComponentFoundation so we can't move it from there. Also there's the issue that cascading defaults apply disabled to everything. This is a bit messy but I'm not sure how to carve out shields. Maybe there's should t inherit ComponentFoundation.

**Comment by MarkStega** [comment]
Not to lose a thought -- World it make sense to have an InteractiveComponent "between" ComponentFoundation & InputComponent/MultiSelectComponent/SingleSelectComponent which implements the Disable? Then have Button derive from InteractiveComponent...

**Comment by simonziegler** [comment]
That is interesting.
