### ISSUE TITLE
MBSelect has various oddities when it renders the menu (Material issue)

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#350]
Example repository provided showing the render issue with MBSelect is https://github.com/Material-Blazor/ComponentRenderIssue. There is a readme in the repository that describes the MBSelect issue. I have another example where the menu is being clipped to a dialog body in Optimi$er that I haven't been able to replicate in the issue program (See #339).

**Comment by MarkStega** [comment]
Observed is that the select menu creates a vertical scrollbar when needed. Unfortunately, it doesn't widen the menu surface so if the menu happens to be fairly short words the scrollbar can effectively make the menu non-readable.
https://github.com/material-components/material-components-web/issues/6709

**Comment by simonziegler** [comment]
Set `MenuSurfacePositioning="@MBMenuSurfacePositioning.Fixed"` on `MBMenu`, `MBSelect` and `MBDatePicker` to fix menu overflow from dialogs. This is a Material.Blazor v2.0.0 enhancement.

@MarkStega to decide when to close this issue regarding material-components/material-components-web#6709.

**Comment by MarkStega** [comment]
According to another poster the issue is with the markup for MBSelect: [https://github.com/material-components/material-components-web/issues/6709#issuecomment-854418774](https://github.com/material-components/material-components-web/issues/6709#issuecomment-854418774)

**Comment by simonziegler** [comment]
@MarkStega can you confirm whether this is still an issue?

**Comment by MarkStega** [comment]
Still an issue with MT12 plus the scrollbar that the select draws appear to be about 1 pixel wide rendering it pretty useless for mouse interaction.

**Comment by MarkStega** [comment]
Everything running properly with M.B 3.0 & Material 14
