### ISSUE TITLE
Datepicker displayed date is misaligned if the style is outlined

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#353]
![chrome_2020-12-01_15-33-07](https://user-images.githubusercontent.com/634561/100793820-b4959d80-33ea-11eb-9db2-a31ef4e29253.png)

**Comment by marinasundstrom** [comment]
It does not align well in a grid layout consisting of other input controls. The Datepicker is wider than the other controls since it has to display its full text. Maybe that is something you have to take into account while designing your app.

**Comment by simonziegler** [comment]
Correct. MB's job is to give you individual components. It's then up to you how you want to align them and set widths, all using CSS or styles. Out of the box, material components web's components lack styling to the grid, and we aim to do no more than repeat what Google give. The date picker is a modified Select and so behaves like any other select. Without doing any sulking work you'll find that selects are typically wider than text fields. So your site will need to control some CSS, which is the same for any web component library.
