### ISSUE TITLE
MBTopAppBar disappears when reducing height of window

### ISSUE THREAD

**Issue by JohnMidity** [Material-Blazor/Material.Blazor#357]
This can be observed also on material-blazor.com.

When the top-bar is scrolled out of view, it immediately should reappear when user scrolls back to the top.
However, when the user scrolls the MBTopAppBar out of view and the resizes the window to the extend that no scrollbars are needed anymore, the topbar is not displayed and is hidden forever.

To reproduce:
1. Go to https://material-blazor.com
2. Reduce the height of the window so the vertical scrollbar gets active.
3. Scroll down as far as possible so the top-bar gets out of view
4. Resize the window (or zoom) until the vertical scrollbar is deactivated.
Observe the missing bar at the top.

**Comment by stefanloerwald** [comment]
I'm suspecting that this is a bug in MDC:

Looking at the DOM, the top bar will get a `top: -128px` on scroll. In code, this is happening at line 30511-30517 of the prettified bundled.min.js:
```js
e.prototype.moveTopAppBar_ = function() {
    if (this.checkForUpdate_()) {
        var t = this.currentAppBarOffsetTop_;
        Math.abs(t) >= this.topAppBarHeight_ && (t = -io.MAX_TOP_APP_BAR_HEIGHT),
        this.adapter.setStyle("top", t + "px")
    }
}
```
This is triggered by `handleTargetScroll, lines 30467 to 30474:
```js
e.prototype.handleTargetScroll = function() {
    var t = Math.max(this.adapter.getViewportScrollY(), 0)
      , e = t - this.lastScrollPosition_;
    this.lastScrollPosition_ = t,
    this.isCurrentlyBeingResized_ || (this.currentAppBarOffsetTop_ -= e,
    this.currentAppBarOffsetTop_ > 0 ? this.currentAppBarOffsetTop_ = 0 : Math.abs(this.currentAppBarOffsetTop_) > this.topAppBarHeight_ && (this.currentAppBarOffsetTop_ = -this.topAppBarHeight_),
    this.moveTopAppBar_())
}
```

Now `handleWindowResize` is just underneath:
```js
e.prototype.handleWindowResize = function() {
    var t = this;
    this.resizeThrottleId_ || (this.resizeThrottleId_ = setTimeout((function() {
        t.resizeThrottleId_ = 0,
        t.throttledResizeHandler_()
    }
    ), io.DEBOUNCE_THROTTLE_RESIZE_TIME_MS)),
    this.isCurrentlyBeingResized_ = !0,
    this.resizeDebounceId_ && clearTimeout(this.resizeDebounceId_),
    this.resizeDebounceId_ = setTimeout((function() {
        t.handleTargetScroll(),
        t.isCurrentlyBeingResized_ = !1,
        t.resizeDebounceId_ = 0
    }
    ), io.DEBOUNCE_THROTTLE_RESIZE_TIME_MS)
}
```

So I'd say the error must be in that resize handling code. It should probably call `handleTargetScroll()` in more situations.

**Comment by simonziegler** [comment]
Looks like this is probably related to the bug below reported on the material-components-web, which their team believes is a bug.

https://github.com/material-components/material-components-web/issues/6589

**Comment by simonziegler** [comment]
Update - this is still present with Material Components Web 12. I asked a progress question at https://github.com/material-components/material-components-web/issues/6589#issuecomment-923166417

**Comment by simonziegler** [comment]
Won't be fixed for Material 2 in https://github.com/material-components/material-components-web. Might work better for Material 3 in https://github.com/material-components/material-web
