### ISSUE TITLE
Implement Timepicker

### ISSUE THREAD

**Issue by marinasundstrom** [Material-Blazor/Material.Blazor#358]
The Timepicker is a very much needed control for business-grade apps.

**Comment by simonziegler** [comment]
Hey Robert, this would be a great addition but isn't something we can get done fast. I'll put this on a backlog.

**Comment by simonziegler** [comment]
@robertsundstrom none of the team developing/maintaining Material.Blazor have a need for a time picker and so we don't have it planned for any time soon. Is this something you might want to work on?

Simon

**Comment by marinasundstrom** [comment]
OK. I have moved on to use MudBlazor instead. They have a complete set of usable controls.
