### ISSUE TITLE
Tooltip dispose timing

### ISSUE THREAD

**Issue by tanekim88** [Material-Blazor/Material.Blazor#361]
In the demo page, it seems that the tooltip lingers a little while even after mouse moves away from it. Is there a setting where I can make it disappear instantly whenever mouse moves away?

**Comment by simonziegler** [comment]
@takekim77, we are just implementing the [Material Components Web tooltip](https://github.com/material-components/material-components-web/tree/v8.0.0/packages/mdc-tooltip). Their JS controls this behaviour and if you look at the methods at the bottom of the linked page, you'll see that there is no way for us to control the timing. I guess this is Google's assessment of how long tooltips should be visible based on conclusions they've drawn from their research.

**Comment by simonziegler** [comment]
This isn't a Material.Blazor issue, and is just MCW's standard tooltip behaviour.
