### ISSUE TITLE
MBButton content

### ISSUE THREAD

**Issue by tanekim88** [Material-Blazor/Material.Blazor#363]
In the documentation, I am only seeing Label attribute to be the only way to fill in the button. But is it possible to fill it with DOM content? Something like this? I tested it but it didn't work.
```
<MBButton>
      <span style="color:blue">Hellow</span><span style="color:yellow">World</span>
</MBButton>
```

With pure material, I can do something like this
```
  <button class="mdc-button mdc-button--outlined">
      <div class="mdc-button__ripple"></div>
      <span style="color:blue">Hellow</span><span style="color:yellow">World</span>
  </button>
```

**Comment by MarkStega** [comment]
This support would actually be pretty easy.

In the Button component we currently have
```
        <span class="mdc-button__label">@Label</span>

```
This would need to be replaced with
```
    @if (!String.IsNullOrEmpty(Label))
    {
         <span class="mdc-button__label">@Label</span>
    }
    @if (ChildContent != null)
    {
        <span class="mdc-button-label">@ChildContent</span>
    }
```
with a corresponding parameter ChildContent as a RenderFragment.

The issues with doing this change are:
1) The button razor file class needs to get changed (easy)
2) The button documentation needs updating (easy addition with the documentation inline with the new parameter)
3) The demo button page should show this (easy)
4) And the kicker (there had to be one, right?): For consistency ALL components with a label should support this functionality; There are 26 components with a label named Label so those and the corresponding demo files need to be changed. We wouldn't want to piecemeal this support with some components having the capability, others not...

We'd welcome a pull request with the changes. If done in the next couple of months this could be part of M-B 2.0

**Comment by simonziegler** [comment]
This falls outside Google's Material Components Web specifications. You can however control the style of the button text with CSS.  First do this:

```
    <MBButton class="my-class" ... etc... />
```

The have the following CSS:

```
.my-class .mdc-button__label {
    color: blue;
}
```

This won't give you that full control that you're after but will get you as close as we can without breaking the spec.

@MarkStega and I will discuss.

**Comment by simonziegler** [comment]
@MarkStega and I discussed this. We will leave this as it is. You can style the whole label with CSS, and it's outside the material theme spec to have more fine grained label styling. Material.Blazor is intentionally a strict and faithful interpretation of Material Theme.
