### ISSUE TITLE
Comment pre-release shield from index.md & readme.md in the final 2.0 PR

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#373]
The 2nd shield in index.md & readme.md needs to be commented out in  the PR destined to be the final 2.0 PR
```
[![NuGet version](https://img.shields.io/nuget/vpre/Material.Blazor?logo=nuget&label=nuget%20pre-release&style=flat-square)](https://www.nuget.org/packages/Material.Blazor/)
```
![devenv_2021-01-04_16-51-58](https://user-images.githubusercontent.com/634561/103583166-43e01600-4ead-11eb-8a3f-e16e2d15291a.png)

**Comment by simonziegler** [comment]
Let's comment it out rather than removing it. We're going to need this in a few months when we get to 3.0.0 previews.

**Comment by MarkStega** [comment]
Then again we could also release 2.0 and then immediately do a 3.0 preview by removing MBToast
