### ISSUE TITLE
ProgressBar of MBDataTable inside MBPagedDataList not displaying

### ISSUE THREAD

**Issue by elite-conveyancing** [Material-Blazor/Material.Blazor#375]

**Comment by simonziegler** [comment]
Hi, can you please give us some detail?

**Comment by elite-conveyancing** [comment]
Hi @simonziegler Thanks for quick reply...I think actually this is working fine. I just created a page with only an MBPagedDataList on, as per your example GitHub source code and added the HasProgressBar and ShowProgress attributes to the inner MBDataTable and sure enough the progress bar displays correctly. It must have been something else causing it not to work on my code. I will review and come back to you if I find anything further but pretty sure you can close this.

Great work by the way and to @MarkStega too. Really enjoying using this Library!

**Comment by simonziegler** [comment]
Thanks for the appreciation! Let's leave this issue open until you've had a chance to find out what's up.
