### ISSUE TITLE
MBCheckboxList

### ISSUE THREAD

**Issue by elite-conveyancing** [Material-Blazor/Material.Blazor#376]
Do you have any plans to add a Checkbox list component which could bind to a list of Values and Labels and expose a list of Checked values? I've tried to implement this using the MBCheckbox but struggled to get the bindings working. Perhaps you could point me in the right direction?

**Comment by elite-conveyancing** [comment]
I believe I need access to the @onchange event of the underlying input, but don't think this is possible via an MBCheckbox?

**Comment by MarkStega** [comment]
I did a very simple wrapper
```
@namespace GeneralComponents

@foreach (var item in pItemList)
{
    <MBCheckbox @key="@item.pLabel"
                @bind-Value="@item.pIsSelected"
                Density="@MBDensity.Minus3"
                Label="@item.pLabel" />
    <br />
}
```
I am reading the content of the array (pItemList) outside of the component and forming my own list of selected elements. You could easily change the bind-Value to Value & add a ValueChanged handler if you want to biuld the list up internally.

**Comment by simonziegler** [comment]
We considered this but in the form you describe it's not really a Material Theme thing. We have a couple of multi selects in version 2 preview 2. Chips and Segmented Buttons. There's a data table spec for multi select with checkboxes that we may implement in v2. Not sure yet whether we'll have the time or will need to put it on the backlog.

**Comment by elite-conveyancing** [comment]
Thanks guys. That will work fine for us. In case it's of use to anyone else who like us are just figuring out all this Blazor stuff, this was our finished working example

```
@page "/checkboxlist"

@foreach (var item in pItemList)
{
    <MBCheckbox @key="@item"
                @bind-Value="@item.pIsSelected"
                Density="@MBDensity.Minus3"
                Label="@item.pLabel" />
    <br />
}

<p>
    @string.Join(", ", SelectedItems.Select(item => item.pLabel))
</p>

@code {

    class pItem
    {
        public string pLabel { get; set; }
        public bool pIsSelected { get; set; }
    }

    List<pItem> pItemList = new List<pItem>
    {
        new pItem { pIsSelected = false, pLabel = "Item 1" },
        new pItem { pIsSelected = false, pLabel = "Item 2" },
        new pItem { pIsSelected = false, pLabel = "Item 3" }
    };

    List<pItem> SelectedItems => pItemList.Where(item => item.pIsSelected).ToList();

}
```

**Comment by simonziegler** [comment]
Cool. I'll close this out for now.
