### ISSUE TITLE
mdc-text-field--fullwidth

### ISSUE THREAD

**Issue by frankhommers** [Material-Blazor/Material.Blazor#379]
I'd like to use `mdc-text-field--fullwidth` on an textfield.

Two questions: 
1) Is there a way to do this manually?
2) Can this be added to Material.Blazor?

Awesome component btw!

**Comment by simonziegler** [comment]
This got removed from material components web 8.0.0 so we can's use it any more (we used to support it). Material.Blazor 1.1.4 uses material components web 7.0.0 but we're no longer developing that. our version 2 in preview jumps to material components web 9.0.0 already, so there's no option for us to support `mdc-text-field--fullwidth`

Sorry for the blizzard of version numbers and thanks for the compliment!
