### ISSUE TITLE
MBTextField bind-Value:event="oninput"

### ISSUE THREAD

**Issue by elite-conveyancing** [Material-Blazor/Material.Blazor#380]
I'm getting MBTextBox to update a property using oninput with a callback event but it seems a bit heavy handed. Is this the correct way to be doing this or is there a built in method more like the bind-Value:event ? This is my working code

```
<MBTextField @bind-Value="@TextBoxValue"
             @oninput="@ValueChanged"
             Label="Outlined Style"
             TextInputStyle="MBTextInputStyle.Outlined" />

<p>@TextBoxValue</p>

@code {
    string TextBoxValue { get; set; }
    void ValueChanged(ChangeEventArgs args)
    {
        TextBoxValue = (string)args.Value;
    }
}
```

**Comment by simonziegler** [comment]
I think you are looking for MBDebouncedTextField here. I don't think using `@bind-Value` with `@oninput` is ever going to work from a Blazor perspective

**Comment by elite-conveyancing** [comment]
Ok, thanks. I'll try with a debounced. The above code does work though.

**Comment by MarkStega** [comment]
Yes, but your ValueChanged is probably not getting called.

@bind-Value generates the equivalent of 

Value=@TextBoxValue
ValueChanged="inline method" that sets the value
ValueExpression="expression" only used in an edit context

(take a look at the razor.g.cs that gets generated).

If you want to handle the change event yourself do the triad and refer to your ValueChanged method in the ValueChanged parameter. If you just want to have the value set just get rid of the @oninput and the ValueChanged method
