### ISSUE TITLE
Q: Animated or pulsing Icons?

### ISSUE THREAD

**Issue by KarloX2** [Material-Blazor/Material.Blazor#383]
I'm new to Material Design and so I'm not sure if I should place this question here.
I saw cool animated/pulsing icons here:

https://material.io/design/iconography/animated-icons.html

Can I have such effects with Material-Blazor, too?

Thanks!

**Comment by MarkStega** [comment]
This isn't on our current list of enhancements so I am going to move the request to the backlog milestone. Of course, if you want to contribute a pull request we'd happily review it and include upon a successful review.

**Comment by KarloX2** [comment]
Hm, I'd like to look into it of course. As I'm a novice, could you provide a hint of two in which direction to start? For example, would you think of a separate class, or rather add features to MBIcon? And also on the material.io page that I linked above I don't see any samples of how to make use in a web app. Do you know where I can find that kind of description?

**Comment by MarkStega** [comment]
I would suggest a new class, MBAnimatedIcon, to start. I searched the Material documentation pages for more detail and it appears to be lacking any guidance. Unlike components (such as a SnackBar: https://material.io/components/snackbars/web) which have detailed html & css guidance, I can't find the corresponding docs for icons of any type. We'll see if @simonziegler can help since he did the original MBIcon implementation.

**Comment by simonziegler** [comment]
I feel that this is beyond Material.Blazor's scope. I personally don't have the programming or graphic design skills to attack this sort of issue, and animations should anyway reflect the branding of the relevant web app, which is something we deliberately eschew in MB.

Animations can of course be CSS or JS based, and sophisticated animation that I've seen involves libraries such as https://greensock.com/gsap/. I don't see how we could meaningfully support a wide variety of paths to animation, even though I love the principle of it.

**Comment by KarloX2** [comment]
I agree. My first impression was that animated icons are a out-of-the-box feature from MDW, but that doesn't seem to be the case. The demos on the https://material.io/design/iconography/animated-icons.html page are videos in fact.
