### ISSUE TITLE
The addition of lodash to the Material.Blazor javascript increases the size of Material.Blazor. js and it's minified companion; In addition, the lodash version that we are using has acritical security flow.

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#385]
Per the title -- Investigate alternatives

**Comment by simonziegler** [comment]
The way we've added lodash debounce and throttle is deprecated and will be obsolete in the next release. We should first investigate the impact of using the preferred inclusion method. If this doesn't work we can look to copy the relevant code in a limited manner, so long as the lodash licence permits us to do so (I think it's MIT).

**Comment by MarkStega** [comment]
![chrome_2021-05-10_17-42-47](https://user-images.githubusercontent.com/634561/117823238-3eb81c80-b23b-11eb-9949-1723c38f915d.png)
The lodash version that we use has a critical security issue.

**Comment by stefanloerwald** [comment]
While the vulnerable method makes it into source code, it is in fact not called, as far as I can tell: we only use lodash for debouncing /throttling and those methods do not end up calling the vulnerable method `template`.

As we don't publically make the lodash methods accessible, the risk here is low, I'd think. We should still update the dependency and work on reducing the amount of code used for debouncing/throttling.
