### ISSUE TITLE
Tooltip on icon on mobile device

### ISSUE THREAD

**Issue by stefanloerwald** [Material-Blazor/Material.Blazor#388]
Tooltips on `MBIcon` do not show on mobile device (Android and iOS). I haven't yet investigated, but perhaps other components are affected too.

**Comment by stefanloerwald** [comment]
Experimenting with MDC directly, I don't think this is a MB issue, but purely MDC. Accordingly, I filed an issue there: https://github.com/material-components/material-components-web/issues/6824

**Comment by stefanloerwald** [comment]
Fixed by https://github.com/material-components/material-components-web/pull/6836. So that should come into MB as soon as it's made part of a release of MCW.

**Comment by simonziegler** [comment]
@stefanloerwald can this be closed now?

**Comment by stefanloerwald** [comment]
While tooltips seem to appear now, they don't disappear. This causes very bad UX when scrolling. Not sure whether that's an issue of MB or MCW.

**Comment by stefanloerwald** [comment]
I don't see tooltips disappearing at all, actually, even on desktops.

**Comment by simonziegler** [comment]
Cannot reproduce, and suspect that this has been fixed along with a prior issue resolution.
