### ISSUE TITLE
MBListItem should have a ripple effect option

### ISSUE THREAD

**Issue by RichardBr** [Material-Blazor/Material.Blazor#397]
I suggest the 'MBListItem' component have an option to enable a ripple effect. 
When this effect is on it will help to emphasise:
- selectable list items with a hover effect
- confirmation of the select item with a ripple effect

I believe this would improve the navigation menu on the demo website.
I'm referring to the code beginning at line 10

```
        <MBListItem LeadingIcon="home" Label="Home" @onclick="@(() => ListItemClickHandler(""))" />
```

in the file `Material.Blazor/Material.Blazor.Website/Shared/MainLayout.razor`

**Comment by RichardBr** [comment]
FYI: I'm currently using the following code for my navigation menu (which largely based on Steve Sanderson's MaterialComponents MdcNavLink.cshtml )

```
<div class="mdc-list">
    <NavLink href="" class="mdc-list-item" Match=NavLinkMatch.All ActiveClass="mdc-list-item--activated">
        <span class="mdc-list-item__ripple"></span>
        <i class="material-icons mdc-list-item__graphic" aria-hidden="true">home</i>
        <span class="mdc-list-item__text">Home</span>
    </NavLink>
    <NavLink href="counter" class="mdc-list-item" Match=NavLinkMatch.All ActiveClass="mdc-list-item--activated">
        <span class="mdc-list-item__ripple"></span>
        <i class="material-icons mdc-list-item__graphic" aria-hidden="true">home</i>
        <span class="mdc-list-item__text">Counter</span>
    </NavLink>
    <NavLink href="fetchdata" class="mdc-list-item" Match=NavLinkMatch.All ActiveClass="mdc-list-item--activated">
        <span class="mdc-list-item__ripple"></span>
        <i class="material-icons mdc-list-item__graphic" aria-hidden="true">home</i>
        <span class="mdc-list-item__text">Fetch data</span>
    </NavLink>
</div>
```
The ripple effect doesn't work properly though :(

**Comment by MarkStega** [comment]
We have no plan to address this but we'd happily review a PR and merge if appropriate,
