### ISSUE TITLE
Initialization of multiple components can lead to poor user experience with server side blazor.

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#399]
If one builds a page or a dialog with many input components (say 50) then the initialization of that page or dialog is unacceptably slow. The 'best guess' cause is that the number of jsinterop calls on initialization is the culprit. This needs to be confirmed. In any case a mitigation strategy is needed.

**Comment by simonziegler** [comment]
Batching JS was implemented to fix this. We also notice that .NET 6 RC1 seems to resolve the performance issue even without batching
