### ISSUE TITLE
Various documentation issues

### ISSUE THREAD

**Issue by simonziegler** [Material-Blazor/Material.Blazor#409]
Fix it.

**Comment by simonziegler** [comment]
Also need good writeup of new blade mechanism where `AddBlade<MyComponent>()` uses `BuildRenderTree` to create the blade's content render fragment.

**Comment by simonziegler** [comment]
Also from the (now closed) #515 issue:

Document generation with DocFx has eight warnings about bad cross references and the two namespace documents are not being created

**Comment by MarkStega** [comment]
The MBBladeSet docs link from the website is broken

**Comment by MarkStega** [comment]
All but two warnings (I believe for the same issue) are left...
