### ISSUE TITLE
Remove material-component-web destroy js function calls

### ISSUE THREAD

**Issue by simonziegler** [Material-Blazor/Material.Blazor#414]
Google indicate that it is best practice to call destroy on initiated elements in order to free up memory, however it is not necessary because browser GC should do the job. We need to remove this mechanism from Material.Blazor because:

- By the time `ComponentBase` calls `Dispose()`, elements have already been removed from the DOM by Blazor.
- Our `destroy()` functions therefore always operate on (and have to ignore) null data.
- This is more the case now due to the introduction of a 10ms to 20ms delay with `BatchingJSRuntime`.
- Trying to call JS on stale elements can cause canceled task exceptions in the batching js runtime, tooltips and cards.

@simonziegler to remove destroy functionality one a thorough review of GC has taken place. @jspuij has recommended reading https://medium.com/swlh/effective-javascript-debugging-memory-leaks-75059b2436f6. @MarkStega and @stefanloerwald both to provide viewpoints here prior to removal.

**Comment by stefanloerwald** [comment]
I have experimented with just MWC ripples and select components and looked at the memory profile of a trivial site to spot leaks. There were none. I vote to remove any call to destroy. Of course this wasn't an exhaustive experiment, but it's enough for me to have trust in modern GCs to clean up after MWC without explicit destroy. It also reduces the amount of times we cross the .NET/JS boundary.

**Comment by MarkStega** [comment]
Agree with the removal...

**Comment by simonziegler** [comment]
Me too. Stefan's experiment extended to 10k selects each with an event handler, matching the most complex MB scenario. Removing these selects without calling destroy freed the memory up in full. We don't need to use `destroy()`

**Comment by stefanloerwald** [comment]
Resolved with #450
