### ISSUE TITLE
M.B. static content don't copy to wwwroot

### ISSUE THREAD

**Issue by PepiBobanov** [Material-Blazor/Material.Blazor#458]
I am new to Blazor.
I tried to make test Blazor WASM project with M.B. from nuget v.2 (i have latest VS2019, project set to .NET5) 
When building the css and js files didn't get copied to wwwroot/_content and it didn't working.

**Comment by stefanloerwald** [comment]
Hi @PepiBobanov 

Static assets aren't usually copied into wwwroot of the consuming project, except on publish. For running in VS, it should suffice to add 
```html
<link href="_content/Material.Blazor/MaterialBlazor.min.css" rel="stylesheet" />
<script src="_content/Material.Blazor/MaterialBlazor.min.js"></script>
```
to your html code.

BR
Stefan

**Comment by PepiBobanov** [comment]
Yes, i did that ,  i read install article (https://material-blazor.com/docs/articles/Installation.html), but in browser i get 404 for those files. Tested Run from IISExpress and like Wasm - same.
Even checked the output directory /bin/framework....
And when published they have other names .
Bad luck may be, this things are so new.

**Comment by PepiBobanov** [comment]
BlazorWASM.StaticWebAssets.xml 
  `<ContentRoot BasePath="_content/Material.Blazor" Path="C:\Users\user\.nuget\packages\material.blazor\2.0.0-preview.1\build\..\staticwebassets\" />`
    
.nuget\packages\material.blazor\2.0.0-preview.1\staticwebassets:
bundled.min.css
bundled.min.js
material-components-icons.css
unbundled.css
unbundled.js
unbundled.min.css
unbundled.min.js

should use 'unbundled.' or 'bundled.' instead 'MaterialBlazor.' ?

**Comment by stefanloerwald** [comment]
The documentation reflects the state of the latest preview, i.e. preview 3. I recommend updating to that preview and using the HTML code I provided in my first comment.

**Comment by PepiBobanov** [comment]
Yes , now it is working as expected.
Thanks

PS: noticed i need to clear nuget cache, and refreh browser (chlear browser cache)
