### ISSUE TITLE
Slider question

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#464]
On behalf of [thecodingcajun@gmail.com
](thecodingcajun@gmail.com)

Hi Mark.

Before I ask my question, I just wanted to tell you that I love the Material Blazor library you guys have put together. It really is amazing and thank you so much for making it available via NuGet.

Quick question (and I apologize if it’s a dumb one), is it possible using the MBSlider to have something like a min value of 0 and a max value of 10 with a single decimal point that increments by .5 instead of .1? I was testing out some stuff this evening and for some reason the increments were always .1 even when I tried playing around with the NumSteps property. 

Again, really appreciate the library!

Thanks!
Michael

**Comment by simonziegler** [comment]
Michael, good question. Without going back into the code I can't remember tbh. Can you watch this space in the coming couple of weeks to see if I've reported back?

**Comment by MarkStega** [comment]
The demo page has multiple sliders  with 'DiscreteWithTicMarks' that are not showing the tics. Temporarily there is a test case added (in vAccessibility branch) which shows some odd tic rendering. It is either a documentation issue or a bug.

**Comment by MarkStega** [comment]
Michael,

It was a bug and will be repaired as soon as the PR that I just submitted gets accepted. When it is merged, the last example will do exactly what you wanted.
