### ISSUE TITLE
Tooltip isShown and hide methods are not exposed.

### ISSUE THREAD

**Issue by tanekim88** [Material-Blazor/Material.Blazor#505]
According to https://material.io/components/tooltips/web#api
There are hide() and isShown()  methods exposed, but they are not exposed in this library.
Please expose these methods, because it's very useful in many cases

(I submitted a pull request to solve the issue mentioned below, not above)

Also, in official material-components-web library exposes mdc global variable, with which I can do something like this 
   mdc.tooltip.numbers.HIDE_DELAY_MS = 0

But how can I do the same with this library?

**Comment by simonziegler** [comment]
Hi @tanekim77 we never got around to dealing with this. Is it still an issue for you?
