### ISSUE TITLE
A way to call material css functions?

### ISSUE THREAD

**Issue by tanekim88** [Material-Blazor/Material.Blazor#506]
If I want to call, for instance, "show-transition($enter-duration)" functions in 
https://material.io/components/tooltips/web#api
is there way to do it using this library?

**Comment by stefanloerwald** [comment]
Absolutely! Bear in mind that those "functions" are just a compile time thing for sass, so just add that mixin to your sass file. You can take inspiration from the website sample styles, e.g. https://github.com/Material-Blazor/Material.Blazor/blob/main/Material.Blazor.Website/Styles/asymmetric-theme.scss

**Comment by tanekim88** [comment]
Thanks @stefanloerwald. That's awesome!
