### ISSUE TITLE
A way to add class to the tooltip div/span

### ISSUE THREAD

**Issue by tanekim88** [Material-Blazor/Material.Blazor#508]
```
<MBTooltip TooltipType="@MBTooltipType.Span">
    <Target>
         Hello
    </Target>
    <Content>
    </Content>
</MBTooltip>
```
is translated into something like 
```
<span aria-describedby="mb-tooltip-2">
         Hello
</span>
```

But I want to have an option to add class to the generated span. Is there way to do it?
I want to be able to do something like 
```
<MBTooltip TooltipType="@MBTooltipType.Span">
    <Target  class="custom-class">
         Hello
    </Target>
    <Content>
    </Content>
</MBTooltip>
```
so that it is translated into 
```
<span aria-describedby="mb-tooltip-2" class="custom-class">
         Hello
</span>
```

**Comment by stefanloerwald** [comment]
The `Target` and `Content` elements inside an MBTooltip are RenderFragments, which do not accept any parameters in Blazor. Therefore, this specific syntax is impossible.

You may need to slightly  adjust your CSS, but you most likely can produce the wanted visual effect, by writing

```html
<MBTooltip TooltipType="@MBTooltipType.Span">
    <Target>
         <span class="custom-class">Hello</span>
    </Target>
    <Content>
    </Content>
</MBTooltip>

```
