### ISSUE TITLE
Random Dispose error

### ISSUE THREAD

**Issue by Johan-allegiance** [Material-Blazor/Material.Blazor#514]
There is a random console error poping up saying that it is trying to dispose something that has already been disposed.

Can you please investigate.? I am using numeric fields, textfields, buttons, segmentbuttons and dialogs.
![image](https://user-images.githubusercontent.com/68000053/125450349-54b41fd8-befc-433d-bc0d-239137b4dbb8.png)

**Comment by MarkStega** [comment]
This is a known issue & should be fixed in preview.07
