### ISSUE TITLE
MBAutocompleteTextField with AllowCustomValue="true" select item event

### ISSUE THREAD

**Issue by elite-conveyancing** [Material-Blazor/Material.Blazor#516]
We are using an **`MBAutocompleteTextField`** with **`AllowCustomValue="true"`** but wanting to react when a selection has been made. Is there an event for that? We only want to fire the event if a selection from the list was made (rather than something typed in) so can't just check for changes on the bound value. Any help/suggestions would be appreciated.

**Comment by elite-conveyancing** [comment]
In fact, I think what we are actually asking for is a way to fill the list from an API service as the user types. Is something like that possible with this control?

**Comment by MarkStega** [comment]
No, there is currently no way to feed the autocomplete list directly from an api; You'd have to update the parameters. The best for the first question would be to compare the value that you get with the list that you supplied.
