### ISSUE TITLE
MBFloatingActionButton markup is generated with the wrong CSS scope

### ISSUE THREAD

**Issue by oliverholliday** [Material-Blazor/Material.Blazor#521]
I put an MBFloatingActionButton on a page but the markup is generated with the wrong 'css scope' (not sure the real term).

For example:

```
<MBCard AutoStyled="false">
    <Primary>
        <h1 class="mdc-typography--heading4">Hello</h1>
        <MBFloatingActionButton Exited="@Exited" Icon="add" class="button-add" />
    </Primary>
</MBCard>
```

Generates the following markup, notice that the CSS scoping attribute is different between the button and the h1.

```
<div class="mdc-card  ">
    <div class="mdc-card__content">
        <div class="">
            <h1 class="mdc-typography--heading4" b-8zucygbup9="">Hello</h1>
            <button class="mdc-fab button-add mdc-ripple-upgraded" _bl_58a5d15d-9ff9-4992-a37c-cdc2d79afb03="" style="--mdc-ripple-fg-size:33px; --mdc-ripple-fg-scale:2.70291; --mdc-ripple-fg-translate-start:12.5px, 21.875px; --mdc-ripple-fg-translate-end:11.5px, 11.5px;">
                <div class="mdc-fab__ripple"></div>
                <i class="material-icons  mdc-fab__icon">add</i>
            </button>
        </div>
    </div>
</div>
```

This means that on a razor component it's hard to target the FAB without using ::deep.

Thanks

**Comment by stefanloerwald** [comment]
There's no scoped CSS attribute on the button at all, as the FAB does not use scoped CSS. You only get scoped CSS attributes on DOM elements that you control.

You are still free to style the FAB any way you want it with the `class` and `style` parameters on the component.

> This means that on a razor component it's hard to target the FAB without using ::deep.

That's the case for absolutely any razor component, so working as intended.
