### ISSUE TITLE
Migration to Material Theme 12

### ISSUE THREAD

**Issue by simonziegler** [Material-Blazor/Material.Blazor#541]
Components to update:

-   [x] Anchor
-   [x] AnimatedNavigation
-   [x] AutocompleteTextField
-   [x] BatchingWrapper
-   [x] BladeSet
-   [x] Button
-   [x] Card
-   [x] Checkbox
-   [x] ChipsSelectMulti
-   [x] ChipsSelectSingle
-   [x] CircularProgress
-   [x] ConfirmationDialog
-   [x] DataTable
-   [x] DatePicker
-   [x] DebouncedTextField
-   [x] Dialog
-   [x] Divider
-   [x] Drawer
-   [x] FloatingActionButton
-   [x] Grid
-   [x] Icon
-   [x] IconButton
-   [x] IconButtonToggle
-   [x] LinearProgress
-   [x] List
-   [x] ListDivider
-   [x] ListItem
-   [x] Menu
-   [x] MenuSelectionGroup
-   [x] MenuSurface
-   [x] NumericDecimalField
-   [x] NumericDoubleField
-   [x] NumericIntField
-   [x] PagedDataList
-   [x] Paginator
-   [x] RadioButton
-   [x] RadioButtonGroup
-   [x] SegmentedButtonMulti
-   [x] SegmentedButtonSingle
-   [x] Select
-   [x] Shield
-   [x] Slider
-   [x] SlidingContent
-   [x] SlidingTabBar
-   [x] Snackbar
-   [x] Switch
-   [x] TabBar
-   [x] TextArea
-   [x] TextField
-   [x] Toast
-   [x] Tooltip
-   [x] TopAppBar
-   [x] TouchTargetWrapper

**Comment by simonziegler** [comment]
Independent code review by @MarkStega and @stefanloerwald:

Components to update:

-   [ ] Anchor
-   [ ] AnimatedNavigation
-   [ ] AutocompleteTextField
-   [ ] BatchingWrapper
-   [ ] BladeSet
-   [ ] Button
-   [ ] Card
-   [ ] Checkbox
-   [ ] ChipsSelectMulti
-   [ ] ChipsSelectSingle
-   [ ] CircularProgress
-   [ ] ConfirmationDialog
-   [ ] DataTable
-   [ ] DatePicker
-   [ ] DebouncedTextField
-   [ ] Dialog
-   [ ] Divider
-   [ ] Drawer
-   [ ] FloatingActionButton
-   [ ] Grid
-   [ ] Icon
-   [ ] IconButton
-   [ ] IconButtonToggle
-   [ ] LinearProgress
-   [ ] List
-   [ ] ListDivider
-   [ ] ListItem
-   [ ] Menu
-   [ ] MenuSelectionGroup
-   [ ] MenuSurface
-   [ ] NumericDecimalField
-   [ ] NumericDoubleField
-   [ ] NumericIntField
-   [ ] PagedDataList
-   [ ] Paginator
-   [ ] RadioButton
-   [ ] RadioButtonGroup
-   [ ] SegmentedButtonMulti
-   [ ] SegmentedButtonSingle
-   [ ] Select
-   [ ] Shield
-   [ ] Slider
-   [ ] SlidingContent
-   [ ] SlidingTabBar
-   [ ] Snackbar
-   [ ] Switch
-   [ ] TabBar
-   [ ] TextArea
-   [ ] TextField
-   [ ] Toast
-   [ ] Tooltip
-   [ ] TopAppBar
-   [ ] TouchTargetWrapper

**Comment by MarkStega** [comment]
Simon - Look at #460; It is more comprehensive as it also looks for potential issues such as using parameters in OnInitAsync. So I've removed the review here and enhanced #460 to include the public attribute comments.
