### ISSUE TITLE
HTML id not working correctly in MBCheckbox

### ISSUE THREAD

**Issue by pablokentch** [Material-Blazor/Material.Blazor#546]
**Describe the bug**
when you go to check in a javascript using HTML id if MBCheckbox is true or false the result is not returned correctly.

Code used for testing

razor file:

```
<div>
    <MBCheckbox id="ischeckcustom" Label="test" @onclick="()=>check_test()"/>
    <p id="demo"></p>
</div>

@code {
	private async Task check_test()
	{
		await js.InvokeAsync<string>("CheckTest");
	}
}
```

JavaScript:

```
function CheckTest() {
	var checkb = document.getElementById("ischeckcustom");

    
	if (checkb.checked == true)
		document.getElementById("demo").innerHTML = "Checkbox true";
	else
		document.getElementById("demo").innerHTML = "Checkbox false";
}
```

not returning **true** or **false**, but **undefined**

if I use the standard html checkbox it works correctly, but the Material blazor checkbox this problem occurs

Here below is the default html checkbox I used

`<input type="checkbox" id="ischeckcustom" @onclick="()=>check_test()"></input>`

**Comment by stefanloerwald** [comment]
Hi @pablokentch,

An `MBCheckBox` is not 100% equivalent to an `input` element with `type="checkbox"`. There is a lot more markup involved, as per Material Design specification. See https://github.com/Material-Blazor/Material.Blazor/blob/main/Material.Blazor/Components/Checkbox/MBCheckbox.razor for the component and markup.

In this file, you'll also see that the ID is applied to the `div` element which surrounds the `input` element. So you will not obtain a reference to the input element in your JS code.

I would recommend against trying to inspect the state via javascript. Instead, bind the value of the checkbox to a boolean property in your component and change markup based on this property:

```html
<MBCheckbox Label="test" @bind-Value="Checked" />
<div id="demo">
   @if (Checked)
   {
      <text>Checkbox true</text>
   }
   else
   {
      <text>Checkbox true</text>
   }
</div>
@code {
   private bool Checked { get; set; }
}
```

Hope that helps,
Stefan
