### ISSUE TITLE
Review icon, color and typography C# classes for removal

### ISSUE THREAD

**Issue by simonziegler** [Material-Blazor/Material.Blazor#83]
These classes seem superflous:

- MdcTypography merely references some mdc classes which are auto completed with intellisense anyway
- MdcColor does the same with some bmdc classes
- MdcIcons just seems unwarranted and is incomplete due to lack of public lists of icons. Font Awesome also add new icons all the time so we should not attempt to keep up with helper constants.

**Comment by MarkStega** [comment]
Agreed
