### ISSUE TITLE
Resolve MdcIconButton

### ISSUE THREAD

**Issue by MarkStega** [Material-Blazor/Material.Blazor#9]
1) Does it still exist or has it been deprecated. Material.io documentation is confusing/contradictory.
2) If it should remain then it needs a demo page.

**Comment by simonziegler** [comment]
It definitely exists, but I forgot to add it to the demo. It should go into the Button page to avoid having too many demo pages.

**Comment by MarkStega** [comment]
Resolved in the ClassMapper cleanup PR
